# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-14 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='subscription_end_date',
        ),
    ]
