# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-14 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagement', '0002_remove_borrower_subscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissuerecord',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='LibraryManagement.Borrower'),
        ),
        migrations.AlterField(
            model_name='bookissuerecord',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='LibraryManagement.Librarian'),
        ),
    ]
