# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 11:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagement', '0002_auto_20170715_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='subscription_end_date',
            field=models.DateField(default=datetime.date(2018, 12, 30)),
        ),
    ]
