# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-14 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagement', '0004_auto_20170714_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissuerecord',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryManagement.Librarian'),
        ),
    ]
